config/routes.rb
Rails.application.routes.draw do

  root to: 'users#top'
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/user/:id', to: 'users#show', via: 'get'
  match '/user/:id/edit_detail', to: 'users#edit_detail', via: 'get', :as => :edit_detail
  match '/users/:id/from_twitter', to: 'users#from_twitter', via: 'get', :as => :from_twitter
  match '/users/:id/save_from_twitter', to: 'users#save_from_twitter', via: 'patch', :as => :save_from_save
  
  resources :users do
  	
  end
  
  resources :applicant_records, only: [:create]
  
  resources :advertising, only: [:create, :new, :edit, :update]
  match '/advertising', to: 'advertising#top', via: 'get', :as => :advertising_top
  match '/advertising/search', to: 'advertising#search', via: 'post', :as => :advertising_search
  match '/advertising/search_result/:search', to: 'advertising#search_result', via: 'get', :as => :advertising_search_result
  
  resources :posts, only: [:create, :new, :edit, :update]
  match '/posts/send', to: 'posts#posts_send', via: 'get', :as => :posts_send
  
  namespace "applicants" do
  	
  end
  

end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
	obfuscatable
	# category
	has_one :category, dependent: :destroy, class_name: 'Category'
	accepts_nested_attributes_for :category
	
	# user
	belongs_to :user
	
	validates :shop_name,
		presence: true,
		length: {maximum: 250, allow_blank: true}
	validates :shop_pref,
		presence: true
	validates :shop_city,
		presence: true
	validates :content,
		length: {minimum: 100}
	
	def Advertising.get_category(val = nil)
		category = Category.all
		
		category.each do |c|
			if c.category == val
				return c.id
			end
		end
	end
	
	def Advertising.search(params)
		
		unless params[:json] == 'json' # 配列を文字に変換
			params[:shop_pref] = params[:shop_pref].join(" ") if params[:shop_pref].present?
			params[:shop_city] = params[:shop_city].join(" ") if params[:shop_city].present?
		end
		
		@search = Advertising.select('shop_name', 'shop_pref', 'shop_city').all
		
		if params[:search].present?
			
			@hiragana = params[:search].tr("ア-ン", "あ-ん")
			@katakana = params[:search].tr("あ-ん", "ア-ン")
			@search = @search.where(("shop_name LIKE ? OR shop_name LIKE ?"), "%#{@hiragana}%","%#{@katakana}%")
		end

		@search = @search.where("shop_pref = ?", "#{params[:shop_pref]}") if params[:shop_pref].present?
		@search = @search.where("shop_city = ?", "#{params[:shop_city]}") if params[:shop_city].present?
		
		category = self.get_category(params[:category][:category]) if params[:category][:category].present?
		@search = @search.where("category_id = ?", "#{category}") if category.present?
		
		if params[:json] == 'json'
			return @search.group("shop_name") 
		else
			return @search.group("shop_name", 'shop_pref', 'shop_city') 
		end
	end
	
	def Advertising.param_parser(params)
		ref_hash = params[:search]
		ref_hash.split("&").map { |v| v.split("=") }
		key_value = Hash[ *ref_hash.split("&").map { |v| v.split("=") }.flatten ]

		Advertising.where("shop_name = ? AND shop_pref = ? AND shop_city = ?", key_value["name"], key_value["pref"], key_value["city"])
	end
end

app/controllers/advertising_controller.rb
class AdvertisingController < ApplicationController

	before_action :set_user, only: [:top, :new, :search_result]

	def top
		@_advertising = Advertising.new #category作成用
		@_advertising.build_category
		
		@advertising = Advertising.page(params[:page]).per(10).order("updated_at DESC")
	end

	def new
		@advertising = Advertising.new
		@advertising.build_category
	end
	
	def update
		params[:advertising][:category_id] = params[:advertising][:category][:category]
		@advertising = Advertising.find_obfuscated(params[:id])
		if @advertising.update(advertising_params)
			flash[:success] = "口コミを更新しました。"
			redirect_to advertising_top_path
		else
			render 'edit'
		end		
	end
	
	def edit
		@advertising = Advertising.find_obfuscated(params[:id])
		@advertising.build_category
	end

	def search
		@search = ""
		if params[:search].present? || params[:shop_pref].present? || params[:shop_city].present? || params[:category][:category].present?
			@search = Advertising.search(params)
		end

		if params[:json] == 'json'
			respond_to do |format|
				format.json{render:json => @search}
			end
		end
		
		@msg = '検索結果は０件でした。' if @search.blank?
	end
	
	def search_result
		@_advertising = Advertising.new #category作成用
		@_advertising.build_category
		
		@advertising = Advertising.param_parser(params)
		@advertising = @advertising.page(params[:page]).per(10).order("updated_at DESC")
	end

	def create
		
		params[:advertising][:category_id] = Advertising.get_category(params[:advertising][:category][:category])
		params[:advertising][:user_id] = current_user.id
		
		@advertising = Advertising.new(advertising_params)
		if @advertising.save
			redirect_to advertising_top_path, :notice => "口コミに投稿しました。"
		else
			@advertising.build_category
			render 'new'
		end
	end

	private

	def set_user
		if current_user.present?
			@user = User.find(current_user.id)
		else
			redirect_to root_path
		end
	end
	
	def advertising_params
		accessible = [:user_id, :content, :ranking, :environment, :friends, :busy, :money, :worthwhile, :flexible, :shop_pref, :shop_city, :shop_name, :category_id, :anonymous, :nickname,
			category_attributes: [:id, :category, :advertising_id]]
		params.require(:advertising).permit(accessible)
	end
end

app/helpers/advertising_helper.rb
module AdvertisingHelper
end

app/views/advertising/_advertising.html.erb
<% @advertising.each do |advertising| %>
<li id="">
  <dl id="" style="margin-bottom: 5px;">
    
    <dd style="text-align: ">
      <a href="#"><span class="shop-name" style="margin:5px;" rel=<%= "pref=#{advertising.shop_pref}&city=#{advertising.shop_city}&name=#{advertising.shop_name}"%>> <%= advertising.shop_name + " " + get_pref_name(advertising.shop_pref) + " " + advertising.shop_city %> </span></a>
    </dd>
    <%= render 'star', {:advertising => advertising}%>
    <dd style="clear:both;">
      <div class="userImage">
        <% if(advertising.anonymous == 0 || advertising.anonymous.nil?) %>
        <% get_user_main_image(advertising.user) %><%= @user_pic %>
        <% else %>
        <%= link_to image_tag("default_image.png", :class => 'user-list-image') %>
        <% end %>
      </div>
    </dd>
    <dd class="userName" style="margin-left: 5px;">
      <% if(advertising.anonymous == 0 || advertising.anonymous.nil?) %>
      <%= get_user_name_with_link(advertising.user) %>
      <% else %>
      <%= advertising.nickname %>
      <% end %>
    </dd>
    <dd class="text" style="margin: 5px;">
      <%= advertising.content %>
    </dd>
    <% if advertising.user_id == current_user.id %>
    <dd class="text" style="text-align: right;margin: 5px;">
      <%= link_to "編集", edit_advertising_path(advertising) %>
    </dd>
    <% end %>
    <dd class="date" style="text-align: right;margin: 5px;">
      <%= advertising.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
    </dd>
  </dl>
</li>
<% end %>

app/views/advertising/_new.html.erb
<%= form_for(@advertising, html:{class: 'form-horizontal'}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="container" style="margin-top:20px;">
  <div class="col col-md-5 col-sm-5">
    <div class="form-group">
      <label for="カテゴリー" class="col col-md-4 col-sm-4 control-label">カテゴリー</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.fields_for @advertising.category do |c| %>
        <%= c.collection_select(:category, Category.group("category").order("id"), :category, :category, {prompt: ""}, {class: "form-control"}) %>
        <% end %>
        <%= f.hidden_field :category_id %>
        <%= f.hidden_field :user_id %>
      </div>
    </div>
    <div class="form-group">
      <label for="アルバイト先場所" class="col col-md-4 col-sm-4 control-label">アルバイト先場所</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.select(:shop_pref, [], {}, { :class => 'area_pref form-control'}) %>
      </div>
    </div>
    <div class="form-group">
      <div class="col col-md-8 col-sm-8 col-md-offset-4 col-sm-offset-4">
        <%= f.select(:shop_city, [], {}, { :class => 'area_city form-control'}) %>
      </div>
    </div>

    <div class="pull-right" id="searched-comment" style="color:red"></div>
    <div id="shop-names"></div>
    <div class="form-group" id="input-shop-name">
      <label for="アルバイト先名称" class="col col-md-4 col-sm-4 control-label">アルバイト先名称</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.text_field :shop_name, class: "form-control", :placeholder => "アルバイト先名称" %>
      </div>
    </div>
  </div>
  <div class="col col-md-7 col-sm-7">
    <div class="form-group">
      <label for="職場の雰囲気" class="col col-md-3 col-sm-3 control-label">職場の雰囲気</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-environment"></div>
      </div>
    </div>

        <div class="form-group">
      <label for="忙しさ" class="col col-md-3 col-sm-3 control-label">忙しさ</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-busy"></div>
      </div>
    </div>
        <div class="form-group">
      <label for="時給" class="col col-md-3 col-sm-3 control-label">時給</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-money"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="友達が出来る" class="col col-md-3 col-sm-3 control-label">友達が出来る</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-friends"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="融通が効く" class="col col-md-3 col-sm-3 control-label">融通が効く</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-flexible"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="やりがい" class="col col-md-3 col-sm-3 control-label">やりがい</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-worthwhile"></div>
      </div>
    </div>
      <div class="form-group">
      <label for="総合評価" class="col col-md-3 col-sm-3 control-label">総合評価</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star"></div>
      </div>
    </div>
    
    <div class="col col-md-8">
    <%= f.text_area :content, placeholder: "口コミ(100文字以上)", class: "form-control", style: "height: 100px;"  %>
    <div class="pull-right">
      <span class="count_textarea"></span><span>文字</span>
    
    </div>
    <div class="form-group" style="marign-top:20px; clear: both;">
      <label for="投稿名" class="col col-md-8 col-sm-8 control-label">投稿名</label>
      <div class="col col col-md-4 col-sm-4">
        <div class="radio-inline">
          <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
        </div>
        <div class="radio-inline" style="margin-left:0px;">
          <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
        </div>
      </div>　
    </div>

    <%= f.submit "登録", class: "btn btn-info btn-lg pull-right", style: "margin:15px;"%>
    </div>
  </div>
  <% end %>

app/views/advertising/_result.html.erb
<% if @search.present? %>
<% @search.each do |search| %>
<a href="#"><span class="shop-name" rel=<%="pref=#{search.shop_pref}&city=#{search.shop_city}&name=#{search.shop_name}"%>><%= search.shop_name + " " + get_pref_name(search.shop_pref) + " " + search.shop_city %></span></a>
<% end %>

<% else %>
<div id="error_explanation">
  <ul>
    <li>
      * <%= @msg %>
    </li>
  </ul>
</div>
<% end %>

app/views/advertising/_search.html.erb
<div class="col col-md-5">
  <%= button_to "新規登録", new_advertising_path, {:method => :get, :class => "btn btn-info btn-lg", :style => "margin-bottom:20px;width: 100%;" } %>

  <%= form_tag advertising_search_path, :method => 'post', remote: true do %>
  <div class="form-group">
    <label for="カテゴリー" class="col col-md-4 col-sm-4 control-label">カテゴリー</label>
    <div class="col col-md-8 col-sm-8">
      <%= fields_for @_advertising.category do |c| %>
      <%= c.collection_select(:category, Category.group("category").order("id"), :category, :category, {promopt: "", :include_blank => true}, {class: "form-control", style: "margin-bottom:20px;" }) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <label for="アルバイト先場所" class="col col-md-4 col-sm-4 control-label">アルバイト先場所</label>
    <div class="col col-md-8 col-sm-8">
      <%= select :shop_pref, "", [], {}, { :class => 'area_pref form-control', :style => "margin-bottom:20px;" } %>
    </div>
  </div>
  <div class="form-group">
    <div class="col col-md-8 col-sm-8 col-md-offset-4 col-sm-offset-4">
      <%= select :shop_city, "", [], {}, { :class => 'area_city form-control', :style => "margin-bottom:20px;" } %>
    </div>
  </div>
  <div class="form-group">
    <label for="アルバイト先名称" class="col col-md-4 col-sm-4 control-label">アルバイト先名称</label>
    <div class="col col-md-8 col-sm-8">
      <%= text_field_tag :search, '', placeholder: "キーワード", class: "form-control" %>
      <%= submit_tag "検索", class: "btn btn-success btn-block", id: "top-advertising-search", style: "margin:20px 0;"%>
      <% end %>
    </div>
  </div>
  
  <div id="shop-names"></div>
</div>

app/views/advertising/edit.html.erb
<%= form_for(@advertising, html:{class: 'form-horizontal'}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="container" style="margin-top:20px;">
  <div class="col col-md-6">
    <div class="form-group">
      <label for="カテゴリー" class="col col-md-4 col-sm-4 control-label">カテゴリー</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.fields_for @advertising.category do |c| %>
        <%= c.collection_select(:category, Category.group("category").order("id"), :id, :category, {selected: @advertising.category_id}, {class: "form-control"}) %>
        <% end %>
        <%= f.hidden_field :category_id %>
      </div>
    </div>
    <div class="form-group">
      <label for="アルバイト先場所" class="col col-md-4 col-sm-4 control-label">アルバイト先場所</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.select(:shop_pref, [@advertising.shop_pref], {}, { :class => 'area_pref form-control'}) %>
      </div>
    </div>
    <div class="form-group">
      <div class="col col-md-8 col-sm-8 col-md-offset-4 col-sm-offset-4">
        <%= f.select(:shop_city, [@advertising.shop_city], {}, { :class => 'area_city form-control'}) %>
      </div>
    </div>
    <div class="form-group">
      <label for="アルバイト先検索" class="col col-md-4 col-sm-4 control-label">アルバイト先検索</label>
      <div class="col col-md-8 col-sm-8">
        <div class="input-group">
          <%= form_tag advertising_search_path, :method => 'post', remote: true do %>
          <%= text_field_tag :search, params[:search], :value => @advertising.shop_name, placeholder: "キーワード", class: "form-control"%>
          <div class="input-group-btn">
            <%= submit_tag "検索", class: "btn", id: "new-advertising-search"%>
            <i class="fa fa-search"></i>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="pull-right" id="searched-comment" style="color:red"></div>
    <div id="shop-names"></div>
    <div class="form-group" id="input-shop-name" style="display:none;">
      <label for="アルバイト先名称" class="col col-md-4 col-sm-4 control-label">アルバイト先名称</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.text_field :shop_name, class: "form-control", :value => @advertising.shop_name, :placeholder => "アルバイト先名称" %>
      </div>
    </div>
  </div>
  <div class="col col-md-6">
    <div class="form-group">
      <label for="職場の雰囲気" class="col col-md-3 col-sm-3 control-label">職場の雰囲気</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-environment"></div>
        <%= hidden_field :advertising_update, :environment, :value => @advertising.environment %>
      </div>
    </div>
    <div class="form-group">
      <label for="忙しさ" class="col col-md-3 col-sm-3 control-label">忙しさ</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-busy"></div>
        <%= hidden_field :advertising_update, :busy, :value => @advertising.busy %>
      </div>
    </div>
    <div class="form-group">
      <label for="時給" class="col col-md-3 col-sm-3 control-label">時給</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-money"></div>
        <%= hidden_field :advertising_update, :money, :value => @advertising.money %>
      </div>
    </div>
    <div class="form-group">
      <label for="友達が出来る" class="col col-md-3 col-sm-3 control-label">友達が出来る</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-friends"></div>
        <%= hidden_field :advertising_update, :friends, :value => @advertising.friends %>
      </div>
    </div>
    <div class="form-group">
      <label for="融通が効く" class="col col-md-3 col-sm-3 control-label">融通が効く</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-flexible"></div>
        <%= hidden_field :advertising_update, :flexible, :value => @advertising.flexible %>
      </div>
    </div>
    <div class="form-group">
      <label for="やりがい" class="col col-md-3 col-sm-3 control-label">やりがい</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star-worthwhile"></div>
        <%= hidden_field :advertising_update, :worthwhile, :value => @advertising.worthwhile %>
      </div>
    </div>
    <div class="form-group">
      <label for="総合評価" class="col col-md-3 col-sm-3 control-label">総合評価</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="edit-star"></div>
        <%= hidden_field :advertising_update, :ranking, :value => @advertising.ranking %>
      </div>
    </div>
    <%= f.text_area :content, placeholder: "口コミ(100文字以上)", class: "form-control", style: "height: 100px;"  %>
    <div class="pull-right">
      <span class="count_textarea"></span><span>文字</span>
    </div>

    <div class="form-group" style="marign-top:20px;clear: both;">
      <label for="投稿名" class="col col-md-8 col-sm-8 control-label">投稿名</label>
      <div class="col col col-md-4 col-sm-4">
        <div class="radio-inline">
          <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
        </div>
        <div class="radio-inline" style="margin-left:0px;">
          <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
        </div>
      </div>
    </div>
    <% if @advertising.anonymous == 0 %>
    <div class="form-group" id="nickname-filed" style="display:none;">
      <% else %>
      <div class="form-group" id="nickname-filed">
        <% end %>
        <label for="投稿名" class="col col-md-8 col-sm-8 control-label">投稿名</label>
        <div class="col col col-md-4 col-sm-4" style="margin-top:5px;">
          <%= f.text_field :nickname, class: "form-control", :value => @advertising.nickname , :placeholder => "匿名" %>
        </div>
      </div>
      <%= f.submit "更新", class: "btn btn-info btn-lg pull-right", id: "update-advertising-btn",  style: "margin:15px;"%>
    </div>

    <% end %>

app/views/advertising/new.html.erb
<%= form_for(@advertising, html:{class: 'form-horizontal'}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="container" style="margin-top:20px;">
  <div class="col col-md-6 col-sm-6">
    <div class="form-group">
      <label for="カテゴリー" class="col col-md-4 col-sm-4 control-label">カテゴリー</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.fields_for @advertising.category do |c| %>
        <%= c.collection_select(:category, Category.group("category").order("id"), :category, :category, {prompt: ""}, {class: "form-control"}) %>
        <% end %>
        <%= f.hidden_field :category_id %>
        <%= f.hidden_field :user_id %>
      </div>
    </div>
    <div class="form-group">
      <label for="アルバイト先場所" class="col col-md-4 col-sm-4 control-label">アルバイト先場所</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.select(:shop_pref, [], {}, { :class => 'area_pref form-control'}) %>
      </div>
    </div>
    <div class="form-group">
      <div class="col col-md-8 col-sm-8 col-md-offset-4 col-sm-offset-4">
        <%= f.select(:shop_city, [], {}, { :class => 'area_city form-control'}) %>
      </div>
    </div>

    <div class="pull-right" id="searched-comment" style="color:red"></div>
    <div id="shop-names"></div>
    <div class="form-group" id="input-shop-name">
      <label for="アルバイト先名称" class="col col-md-4 col-sm-4 control-label">アルバイト先名称</label>
      <div class="col col-md-8 col-sm-8">
        <%= f.text_field :shop_name, class: "form-control", :placeholder => "アルバイト先名称" %>
      </div>
    </div>
  </div>
  <div class="col col-md-6 col-sm-6">
    <div class="form-group">
      <label for="職場の雰囲気" class="col col-md-3 col-sm-3 control-label">職場の雰囲気</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-environment"></div>
      </div>
    </div>

        <div class="form-group">
      <label for="忙しさ" class="col col-md-3 col-sm-3 control-label">忙しさ</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-busy"></div>
      </div>
    </div>
        <div class="form-group">
      <label for="時給" class="col col-md-3 col-sm-3 control-label">時給</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-money"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="友達が出来る" class="col col-md-3 col-sm-3 control-label">友達が出来る</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-friends"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="融通が効く" class="col col-md-3 col-sm-3 control-label">融通が効く</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-flexible"></div>
      </div>
    </div>
            <div class="form-group">
      <label for="やりがい" class="col col-md-3 col-sm-3 control-label">やりがい</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star-worthwhile"></div>
      </div>
    </div>
      <div class="form-group">
      <label for="総合評価" class="col col-md-3 col-sm-3 control-label">総合評価</label>
      <div class="col col col-md-8 col-sm-8" style="margin-top:5px;">
        <div id="star"></div>
      </div>
    </div>
    
    
    <%= f.text_area :content, placeholder: "口コミ(100文字以上)", class: "form-control", style: "height: 100px;"  %>
    <div class="pull-right">
      <span class="count_textarea"></span><span>文字</span>
    
    </div>
    <div class="form-group" style="marign-top:20px; clear: both;">
      <label for="投稿名" class="col col-md-8 col-sm-8 control-label">投稿名</label>
      <div class="col col col-md-4 col-sm-4">
        <div class="radio-inline">
          <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
        </div>
        <div class="radio-inline" style="margin-left:0px;">
          <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
        </div>
      </div>　
    </div>
    <div class="form-group" id="nickname-filed" style="display:none;">
      <label for="投稿名" class="col col-md-8 col-sm-8 control-label">投稿名</label>
      <div class="col col col-md-4 col-sm-4" style="margin-top:5px;">
        <%= f.text_field :nickname, class: "form-control", :placeholder => "匿名" %>
      </div>
    </div>
    <%= f.submit "登録", class: "btn btn-info btn-lg pull-right", style: "margin:15px;"%>
    
  </div>
  <% end %>

app/views/advertising/search.js.erb
$('#shop-names').html("<%= escape_javascript(render 'result')%>");

app/views/advertising/search_result.html.erb
<%= render 'search' %>

<div class="col col-md-7">
  <ul class="nav nav-tabs">
    <li>
      <%= link_to "みんなの口コミ情報・最新", advertising_top_path %>
    </li>
    <li>
      <%= link_to "みんなの口コミ情報・検索結果", advertising_search_result_path %>
    </li>
  </ul>
  <div id="advertise">
    <%= paginate(@advertising) %>
    <div id="advertise-title" class="panel panel-default" style="padding-left:20px;">
      <i class="fa fa-comment"></i> 　口コミ検索結果
    </div>

    <ul class="list-unstyled">
      <%= render 'advertising' %>
    </ul>
    <%= paginate(@advertising) %>
  </div>
</div>