config/routes.rb
Rails.application.routes.draw do

  root to: 'users#top'
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/user/:id', to: 'users#show', via: 'get'
  match '/user/:id/edit_detail', to: 'users#edit_detail', via: 'get', :as => :edit_detail
  match '/users/:id/from_twitter', to: 'users#from_twitter', via: 'get', :as => :from_twitter
  match '/users/:id/save_from_twitter', to: 'users#save_from_twitter', via: 'patch', :as => :save_from_save
  
  resources :users do
  	
  end
  
  resources :applicant_records, only: [:create]
  
  resources :advertising, only: [:create, :new, :edit, :update]
  match '/advertising', to: 'advertising#top', via: 'get', :as => :advertising_top
  match '/advertising/search', to: 'advertising#search', via: 'post', :as => :advertising_search
  match '/advertising/search_result/:search', to: 'advertising#search_result', via: 'get', :as => :advertising_search_result
  
  resources :posts, only: [:create, :new, :edit, :update]
  match '/posts/send', to: 'posts#posts_send', via: 'get', :as => :posts_send
  
  namespace "applicants" do
  	
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
	obfuscatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:omniauthable, :timeoutable, :token_authenticatable#, :confirmable
         
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  
  # paperclip main_picture
  has_attached_file :picture, 
  	:style => {
  		:thumb => "100×100",
  		:medium => "200×200",
  		:large => "300×300",
  	},
  	:storage => :s3,
  	:s3_permissions => :private,
  	:s3_credentials => "#{Rails.root}/config/s3.yml",
  	:url => "s3_domain_url",
  	:hash_secret => "fjwoefjc4902rj3jgojmfdsf9wfwvzagjl",
  	:path => ":attachment/:id/:hash.:extension"
  validates_attachment_size :picture, :less_than => 1.megabytes, :attachment_presence => true
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  #paperclip sub_picutres
	has_many :images, :as => :imageable, dependent: :destroy
	accepts_nested_attributes_for :images
	
	#applicant
	has_one :applicant, dependent: :destroy
	accepts_nested_attributes_for :applicant
	
	#applicant_edu_records
	has_many :edu_records, dependent: :destroy, class_name: 'ApplicantEduRecord'
	accepts_nested_attributes_for :edu_records
	
	#applicant_arbeit_records
	has_many :arbeit_records, dependent: :destroy, class_name: 'ApplicantArbeitRecord'
	accepts_nested_attributes_for :arbeit_records
	
	#applicant_wish_jobs
	has_many :wish_jobs, dependent: :destroy, class_name: 'ApplicantWishJob'
	accepts_nested_attributes_for :wish_jobs
	
	#applicant_status
	has_one :status, dependent: :destroy, class_name: 'ApplicantStatus'
	accepts_nested_attributes_for :status
	
	#advertising
	has_many :advertising
	
	#post
	has_many :posts
	
	#push
	has_many :pushes
  
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates :family_name,
  	length: { maximum: 10 }
  validates :first_name,
  	length: { maximum: 10 }
 	validates_uniqueness_of :email
 	validates_presence_of(:family_name)
 	validates_presence_of(:first_name)
  
  def self.find_for_oauth(auth, signed_in_resource = nil)
  	
  	identity = Identity.find_for_oauth(auth)
  	user = signed_in_resource ? signed_in_resource : identity.user

  	if user.nil?
  		email_is_verified = auth.info.email # && (auth.info.verified || auth.info.verified_email)
  		email = auth.info.email if email_is_verified
  		user = User.where(:email => email).first if email

  		# facebook/twitter
  		if user.nil?
  			user = User.new(
  			family_name: auth.extra.raw_info.last_name.present? ? auth.extra.raw_info.last_name : 'pending',
  			first_name: auth.extra.raw_info.first_name.present? ? auth.extra.raw_info.first_name : 'pending',
  			email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
  			password: Devise.friendly_token[0,20],
  			gender: (auth.extra.raw_info.gender == "male" || auth.extra.raw_info.gender == "男性" || auth.extra.raw_info.gender.nil? ) ? "男性" : "女性",
  			confirmed_at: Time.now.to_s(:db)
  			)
  			
  			#user.skip_confirmation!
  			user.save!
  			
  		end
  	end
  	
  	if identity.user != user
  		identity.user = user
  		identity.save!
  	end
  	user
  end
  
  def email_verified?
  	self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_detail, :save_from_twitter]
	
	def before_login
		
	end
	
	def show
		redirect_to root_path if @user.open == 1
		@posts = @user.posts.page(params[:page]).per(10).order("updated_at DESC")
		@post = Post.new
		
		@is_my_page = true if current_user.id.to_i == @user.id.to_i
		@this_page_params_user_id = @user.id.to_i
		
		# delete push
		if params[:id].to_i == current_user.id.to_i
			Push.destroy_all(user_id: current_user.id)
			session[:push_count] = nil
		end
	end

	def index
	end

	def edit
		@edu_records = @user.edu_records
		@arbeit_records = @user.arbeit_records
		@applicant = @user.applicant
		
		# 新規作成用
		@user.images.build unless @user.images.any?
		@user.build_applicant if @applicant.nil?
		
		(3 - @edu_records.count ).times {
			@user.edu_records.build
		} unless @edu_records.any?
		
		(4 - @arbeit_records.count).times {
			@user.arbeit_records.build
		} unless @arbeit_records.any?
	end
	
	def edit_detail
		@wish_jobs = @user.wish_jobs
		@applicant = @user.applicant
		
		@status = @user.status
		@user.build_status if @status.nil?
		
		# 新規作成
		@user.build_applicant if @applicant.nil?
		
		(3 - @wish_jobs.count ).times {
			@user.wish_jobs.build
		} unless @wish_jobs.any?
	end
	
	# 後回し	
	def create_record
		@user = User.find_obfuscated(current_user.id)

		self.edit
		@user.edu_records.build
		#respond_to do |format|
		#format.html {render :file => "users/edit"}
		#end
	end
	
	def top
		if current_user
			@user ||= current_user
			
			# 初めに投稿を促す
			@have_advertising = @user.advertising
			unless @have_advertising.any?
				@advertising = Advertising.new
				@advertising.build_category
			end
			
			@users = User.where.not(id: current_user.id)
			@users = @users.where(open: 0)
			@post = Post.new
		else
			render 'before_login'
		end
	end
	
	def from_twitter
		@user = User.find_obfuscated(params[:id])
	end
	
	def save_from_twitter
		if @user.update(user_params)
			flash[:success] = "確認メールを、登録したメールアドレス宛に送信しました。メールに記載されたリンクを開いてアカウントを有効にして下さい。"
			redirect_to root_path
		else
			render 'from_twitter'
		end		
	end

	def update
		_params = user_params

		self.save_sub_image

		if _params.present? && @user.update(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def finish_signup

	end

	def save_sub_image
		# imagesの登録
		unless params[:images].nil?
			params[:images].each { |image|
				@user.images.create(image: image)
			}
		end
	end

	private

	def set_user
		begin
			@user = User.find_obfuscated(params[:id])
		rescue
			redirect_to root_path
		end
	end

	def user_params
		accessible = [ :family_name,:first_name, :email, :birthday, :open, :gender,
			
			 applicant_attributes: [:address_pref, :address_city, :self_apeal, :belonging, :monday_ok_flag,
			 	:monday_ok_from_time, :monday_ok_to_time, :tuesday_ok_flag, :tuesday_ok_from_time, :tuesday_ok_to_time,
			 	:wednesday_ok_flag, :wednesday_ok_from_time, :wednesday_ok_to_time, :thursday_ok_flag, :thursday_ok_from_time,
			 	:thursday_ok_to_time, :friday_ok_flag, :friday_ok_from_time, :friday_ok_to_time, :saturday_ok_flag, :saturday_ok_from_time,
			 	:saturday_ok_to_time, :sunday_ok_flag, :sunday_ok_from_time, :sunday_ok_to_time, :gakko_name , :self_introduce, :id ],
			 	
			 edu_records_attributes: [:name, :from_year, :from_month, :to_year, :to_month, :id ],
			 
			 arbeit_records_attributes: [:name, :from_year, :from_month, :to_year, :to_month, :id ],
			 
			 status_attributes: [:id, :status],
			 
			 wish_jobs_attributes: [:wish_job_name, :wish_payment, :wish_placement, :id]]
			 #images_attributes: [:id, :image_file_name, :image_content_type, :image_file_size, :image_update_at, :imageable_id, :imageable_type] ]
			 
		accessible = [ :picture ] if params[:user].present? && params[:user][:picture].present?
		#raise
		unless params[:user].blank?
			accessible << [ :password, :password_confirmation ]
			params.require(:user).permit(accessible)
		end
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_arbeit_record.html.erb
<% @user.arbeit_records.each_with_index do |record_s, count| %>
<%= f.fields_for :arbeit_records, record_s do |f_record_s| %>
<div class="form-group" style="clear: both;">
  <% if count == 0 %>
  <label for="アルバイト履歴" class="col col-md-3 col-sm-3 col-xs-12 control-label">アルバイト履歴</label>
  <div class="col col col-md-9 col-sm-9 col-xs-12">
    <% else %>
    <div class="col col-md-9 col-sm-9 col-md-offset-3 col-sm-offset-3 col-xs-12" style="margin-top:20px;">
      <% end %>
      <div class="row">
        <div class="col col col-md-3 col-sm-3 col-xs-6">
          <%= f_record_s.text_field :from_year, class: "form-control", placeholder: "年" %>
        </div>
        <div class="col col col-md-2 col-sm-2 col-xs-6" style="padding-left:0px;">
          <%= f_record_s.text_field :from_month, class: "form-control", placeholder: "月"%>
        </div>
        <div class="col col col-md-1 col-sm-1">
          〜
        </div>
        <div class="col col col-md-3 col-sm-3 col-xs-6">
          <%= f_record_s.text_field :to_year, class: "form-control", placeholder: "年" %>
        </div>
        <div class="col col col-md-2 col-sm-2 col-xs-6" style="padding-left:0px;">
          <%= f_record_s.text_field :to_month, class: "form-control", placeholder: "月" %>
        </div>
      </div>
      <%= f_record_s.text_field :name, class: "form-control", placeholder: "アルバイト履歴", style: "margin-top:10px;"%>
    </div>
  </div>
  <% end %>
  <% end %>
  <!-- ><a href="#"><i id="arbeit-add" class="fa fa-plus-circle pull-right fa-2x" style="margin-top:10px;"></i></a><-->
  <%= f.submit "更新", class: "btn btn-info pull-right", style: "clear:both;margin:20px 0;" %>

app/views/users/_edu_record.html.erb
    <% @user.edu_records.each_with_index do |record, count| %>
    <%= f.fields_for :edu_records, record do |f_record| %>
    <div class="form-group" style="clear: both;">
      <% if count == 0 %>
      <label for="学歴" class="col col-md-3 col-sm-3 col-xs-12 control-label">学歴・職歴</label>
      <div class="col col col-md-9 col-sm-9 col-xs-12">
        <% else %>
        <div class="col col-md-9 col-sm-9 col-md-offset-3 col-sm-offset-3 col-xs-12" style="margin-top:20px;">
          <% end %>
          <div class="row">
            <div class="col col col-md-3 col-sm-3 col-xs-6">
              <%= f_record.text_field :from_year, class: "form-control", placeholder: "年" %>
            </div>
            <div class="col col col-md-2 col-sm-2 col-xs-6" style="padding-left:0px;">
              <%= f_record.text_field :from_month, class: "form-control", placeholder: "月"%>
            </div>
            <div class="col col col-md-1 col-sm-1">
              〜
            </div>
            <div class="col col col-md-3 col-sm-3 col-xs-6">
              <%= f_record.text_field :to_year, class: "form-control", placeholder: "年" %>
            </div>
            <div class="col col col-md-2 col-sm-2 col-xs-6" style="padding-left:0px;">
              <%= f_record.text_field :to_month, class: "form-control", placeholder: "月" %>
            </div>
          </div>

          <%= f_record.text_field :name, class: "form-control", placeholder: "学歴・職歴", style: "margin-top:10px;"%>
        </div>
      </div>
      <% end %>
      <% end %>
      <!-- ><a href="#"><a href="#" id="edu-add"><i class="fa fa-plus-circle pull-right fa-2x" style="margin-top:10px;"></i></a><-->
      <%= f.submit "更新", class: "btn btn-info pull-right", style: "clear:both;margin:20px 0;" %>

app/views/users/_picture.html.erb
<div class="panel-body">

  <div class="form-group">
    <p>
      <%= f.label 'メインピクチャ', class: "control-label" %>
    </p>
    <a data-toggle="modal" href="#modal-picture" class="modal-picture"> <%= image_tag("https://s3-ap-northeast-1.amazonaws.com/arbeit-static/" + @user.picture.path, data: {toggle: 'modal'}, data: {target: '#img_modal'}, :id => "main-picture", :style => "width: 200px; height:100%;") if @user.picture.path.present? %> </a>

    <%= f.file_field :picture %>
    <%= f.submit "更新", class: "btn btn-info pull-right" %>
    <p>
      <label for="サブピクチャ" class="control-label" style="margin-top:20px;">サブピクチャ</label>
    </p>
    <% @user.images.each do |pic| %>
    <a data-toggle="modal" href="#modal-picture" class="modal-picture"> <%= image_tag("https://s3-ap-northeast-1.amazonaws.com/arbeit-static/" + pic.image.path, :style => "width: 90px; height:100%;paddign-right:5px;padding-bottom:5px;") if pic.image.path.present? %> </a>
    <% end %>
    <%= file_field_tag "images[]", type: :file, multiple:true %>
    <%= f.submit "更新", class: "btn btn-info pull-right" %>
  </div>
</div>
<%= render 'shared/picutre_modal' %>

app/views/users/_user_info.html.erb
<li id="profile-image-box">
  <% get_main_image %><%= @main_image %>
</li>
<li>
  <span class="size20"　style="text-align:left;"><strong>名前：　<%= @user.family_name + " " + @user.first_name %></strong></span>
</li>
</ul>
<ul class="list-unstyled">
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>自己紹介：<%= get_applicant_data(@user, "self_introduce") %> </span>
  </li>
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>居住地：<%= get_address_name(@user) %> </span>
  </li>
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>年齢：<%= get_age(@user) %></span>
  </li>
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>属性：<%= get_applicant_data(@user, "belonging") %></span>
  </li>
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>大学名：<%= get_applicant_data(@user, "gakko_name") %></span>
  </li>
  <li style="margin-bottom:5px;border-bottom: 1px solid #ececec;">
    <span>沿線：<%= get_applicant_data(@user, "railway_line") %> </span>
  </li>

  <% get_arbeit_records %><%= @arbeit_records%>
  <% get_wish_jobs %><%= @wish_jobs%>
  <% get_sub_images %><%= @sub_images%>
  <%= render 'shared/picutre_modal' %>

app/views/users/_user_list_pc.html.erb
<div class="visible-sm visible-md visible-lg">
  <% @users.each_with_index do |user, count| %>

  <div class="col col-md-3 col-sm-3 col-lg-3">
    <div class="user-list-image-box">
      <% get_user_main_image(user) %><%= @user_pic %>
    </div>
    <a data-toggle="modal" href="#q_and_a" class="message btn btn-info pull-right">Q&Aを送る</a>
    <div style="min-height: 120px;">
      <div class="panel panel-default user-list-comment">

        <div class="panel-heading user">
          <ul class="list-unstyled">
            <li>
              <%= user.gender %>
            </li>
            <li>
              <%= get_age(user) %> <%= "歳" if user.birthday.present?  %>
            </li>
            <li>
              <%= get_address_name(user) %>
            </li>
            <li>
              <%= user.applicant.applicant_status if user.applicant.present? && user.applicant.applicant_status.present? %>
            </li>
            <li>
              <%= user.applicant.belonging if user.applicant.present? && user.applicant.belonging %>
            </li>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user, html:{class:'form-horizontal', multipart: true}) do |f|  %>
<%= render 'shared/error_messages', object: f.object %>
<div class="container">
  <div class="col col-md-5 col-sm-5">
    <%= render 'picture', {:f=>f} %>
  </div>

  <div class="col col-md-7 col-sm-7">
    <ul class="nav nav-tabs" style="margin-bottom:20px;">
      <li>
        <%= link_to "基本情報", edit_user_path %>
      </li>
      <li>
        <%= link_to "アピる", edit_detail_path %>
      </li>
    </ul>

    <div class="form-group">
      <label for="公開設定" class="col col-md-3 col-sm-3 control-label">公開設定</label>
      <div class="col col col-md-9 col-sm-9">
        <div class="radio-inline">
          <label><%= f.radio_button :open, "0", {:checked => true }%>公開</label>
        </div>
        <div class="radio-inline" style="margin-left:0px;">
          <label><%= f.radio_button :open, "1" %>非公開</label>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="名前" class="col col-md-3 col-sm-3 control-label">名前</label>
      <div class="col col col-md-4 col-sm-4">
        <%= f.text_field :family_name, class: "form-control", placeholder: "姓"  %>
      </div>
      <div class="col col col-md-5 col-sm-5">
        <%= f.text_field :first_name, class: "form-control", placeholder: "名"  %>
      </div>
    </div>

    <div class="form-group">
      <label for="生年月日" class="col col-md-3 col-sm-3 control-label" style="margin-top:10px;">生年月日</label>
      <div class="col col col-md-9 col-sm-9">
        <%== sprintf(f.date_select(:birthday, {:use_month_numbers=>true, :date_separator => '%s', :end_year=>1960,  :start_year=> Time.now.year - 15, :default =>'1990-1-1'.to_date}, {:class => "form-control", :style => "width: 90px;display: inline-block; margin-top:10px;"}), '年','月') %>
      </div>
    </div>
    <%= f.fields_for :applicant do |applicant| %>
    <div class="form-group">
      <label for="現住所" class="col col-md-3 col-sm-3 control-label" style="margin-top:20px;">現住所</label>
      <div class="col col col-md-9 col-sm-9">
        <%= applicant.select(:address_pref, [@user.applicant.address_pref], {}, { :class => 'area_pref form-control', :style => "margin-top:10px;"}) %>
        <%= applicant.select(:address_city, [@user.applicant.address_city], {}, { :class => 'area_city form-control', :style => "margin-top:10px;"})%>
      </div>
    </div>
    <div class="form-group">
      <label for="所属" class="col col-md-3 col-sm-3 control-label">所属</label>
      <div class="col col-md-9 col-sm-9">
        <%= applicant.text_field :belonging, class: "form-control", :value => @user.applicant.belonging, :placeholder => "学生・フリーターなど" %>
      </div>
    </div>
    <div class="form-group">
      <label for="学校名" class="col col-md-3 col-sm-3 control-label">学校名</label>
      <div class="col col-md-9 col-sm-9">
        <%= applicant.text_field :gakko_name, class: "form-control", :value => @user.applicant.gakko_name, :placeholder => "学校名など" %>
      </div>
    </div>
    <div class="form-group">
      <label for="自己紹介" class="col col-md-3 col-sm-3 control-label">自己紹介</label>
      <div class="col col-md-9 col-sm-9">
        <%= applicant.text_area :self_introduce, placeholder: "自己紹介(200文字以内)", class: "form-control", style: "height: 100px;" %>
      </div>
    </div>
    <% end %>
    <%= f.submit "更新", class: "btn btn-info pull-right", style: "margin:20px 0;"%>
    <%= render 'edu_record', {:f=>f}%>
    <%= render 'arbeit_record', {:f=>f}%>
  </div>
</div>
<!--  -->
<% end %>

app/views/users/edit_detail.html.erb
<%= form_for(@user, html:{class:'form-horizontal', multipart: true}) do |f|  %>
<div class="container">
  <div class="col col-md-5 col-sm-5">
    <%= render 'picture', {:f=>f} %>
  </div>
  <div class="col col-md-7 col-sm-7">
    <ul class="nav nav-tabs" style="margin-bottom:20px;">
      <li>
        <%= link_to "基本情報", edit_user_path %>
      </li>
      <li>
        <%= link_to "アピる", edit_detail_path %>
      </li>
    </ul>
    <%= render 'wish_job', {:f => f}%>
    <%= render 'wish_time', {:f => f}%>
  </div>
  <%= f.submit "更新", class: "btn btn-info pull-right", style: "margin:10px 20px 20px 0;"%>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= notice %>
  <div class="row">
    <div class="col col-md-6 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <ul class="list-unstyled">
            <li class="pull-right">
              <% if @is_my_page %>
              <%= button_to "編集", edit_user_path(@user), {:method => :get, :id => "profile-update", :class => "btn btn-info pull"} %>
              <% end %>
            </li>
            <%= render 'user_info' %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col col-md-6 col-sm-6">
      <%= render 'posts/post_nav'%>
      <%= render 'posts/get_posts'%>
    </div>
  </div>

app/views/users/top.html.erb
<div class="container">
  <div class="row">
    <div class="col col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <ul class="list-unstyled">
            <li class="pull-right">
              <%= button_to "編集", edit_user_path(@user), {:method => :get, :id => "profile-update", :class => "btn btn-info pull"} %>
            </li>
            <%= render 'user_info' %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col col-md-8">
      <ul class="nav nav-tabs" style="margin-bottom:20px;">
        <li>
          <%= link_to "ユーザーを見る", root_path %>
        </li>
        <li>
          <a href="#">店舗・店長を見る(comming soon)</a>
        </li>
        <li>
          <%= link_to "口コミ掲示板", advertising_top_path %>
        </li>
      </ul>
      <%= render 'user_list_pc' %>
      <%= render 'user_list_sp' %>
    </div>
  </div>

  <!-- modal -->
  <div class="modal" id="q_and_a">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
          </button>
        </div>
        <div class="panel panel-default" style="margin-bottom:10px;">
          <div class="panel-heading">

            <%= form_for(@post, html:{class:'form-horizontal'}) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.text_area :content, placeholder: "Q&A...", class: "form-control", style: "height: 80px;"%>

            <div class="form-group" style="margin-bottom: 0px;">
              <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
              <div class="col col col-md-4 col-sm-4">
                <div class="radio-inline">
                  <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
                </div>
                <div class="radio-inline" style="margin-left:0px;">
                  <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
                </div>
              </div>
              <%= f.hidden_field :user_id %>
              <%= f.hidden_field :send_user_id %>
              <div class="col col col-md-6 col-sm-6">
                <%= f.submit "投稿", class: "btn btn-info", style: "width:100%;margin-top:5px;"%>
              </div>
            </div>
            <div class="form-group" id="nickname-filed" style="display:none;margin-bottom: 0px;">
              <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
              <div class="col col col-md-4 col-sm-4" style="margin-top:5px;">
                <%= f.text_field :nickname, class: "form-control", :placeholder => "匿名" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <% unless @have_advertising.any? %>
  <div class="modal" id="advertising-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="color: rgb(127, 68, 10);font-weight: bold;">
          <div style="text-align: center;font-size:25px;">
            今ならアルバイトの口コミ投稿をすると、スターバックスコーヒー券が貰えます！
            <%= image_tag("starbucks.png", :style => 'widht:70px;height:70px;') %>
          </div>
          ※限定50名の先着順になります。
          <div class="row">
            <div class="col col-md-4" style="text-align: center;">
              <%= image_tag("starbucks-post.png", :style => 'widht:50px;height:50px;') %>
              <div>
                ①やっている・やっていたバイト先の
                <br>
                口コミ情報を登録する
                <br>
                ※プロフィール写真のご登録はお願いします。
              </div>
            </div>
            <div class="col col-md-4" style="text-align: center;">
              <%= image_tag("starbucks-mail.png", :style => 'widht:50px;height:50px;') %>
              <div>
                ②登録したメールアドレス宛てに、
                <br>
                24時間以内に500円分のチケットが届きます。
              </div>
            </div>
            <div class="col col-md-4" style="text-align: center;">
              <%= image_tag("starbucks-go.png", :style => 'widht:50px;height:50px;') %>
              <div>
                ③店舗にて、お好きなドリンクが楽しめます。
              </div>
            </div>
          </div>
          
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
          </button>
        </div>
        <div class="modal-body" style="color: #000000;font-weight: nomal;">
          <%= render 'advertising/new'%>
        </div>
      </div>
    </div>
  </div>
  <% end %>