config/routes.rb
Rails.application.routes.draw do

  root to: 'users#top'
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/user/:id', to: 'users#show', via: 'get'
  match '/user/:id/edit_detail', to: 'users#edit_detail', via: 'get', :as => :edit_detail
  match '/users/:id/from_twitter', to: 'users#from_twitter', via: 'get', :as => :from_twitter
  match '/users/:id/save_from_twitter', to: 'users#save_from_twitter', via: 'patch', :as => :save_from_save
  
  resources :users do
  	
  end
  
  resources :applicant_records, only: [:create]
  
  resources :advertising, only: [:create, :new, :edit, :update]
  match '/advertising', to: 'advertising#top', via: 'get', :as => :advertising_top
  match '/advertising/search', to: 'advertising#search', via: 'post', :as => :advertising_search
  match '/advertising/search_result/:search', to: 'advertising#search_result', via: 'get', :as => :advertising_search_result
  
  resources :posts, only: [:create, :new, :edit, :update]
  match '/posts/send', to: 'posts#posts_send', via: 'get', :as => :posts_send
  
  namespace "applicants" do
  	
  end
  

end

app/models/post.rb
class Post < ActiveRecord::Base
	obfuscatable
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		params[:post][:send_user_id] = current_user.id
		
		# get user_id from user show page. if top page, it has
		# params[:post][:user_id] = URI(request.referer).path.delete("/users/") if params[:post][:user_id].nil?
		
		@post = Post.new(post_params)
		if @post.save
			# make push data
			Push.create(user_id: params[:post][:user_id])
			
			redirect_to URI(request.referer).path, :notice => "Q&Aを投稿しました。"
		else
			render user_path(params[:post][:user_id])
		end
	end
	
	def posts_send
		@user = User.find(current_user.id)
		@posts = Post.where("send_user_id = ?", current_user.id).page(params[:page]).per(10).order("updated_at DESC")
		@is_my_page = true if current_user.id.to_i == @user.id.to_i # my page can see send_message
		@this_page_params_user_id = @user.id.to_i # for hidden value of user_id to send message
		@send = 'send' # difference from users/top
	end
	
	def edit
		@post = Post.find_obfuscated(params[:id])
	end
	
	def update
		@post = Post.find_obfuscated(params[:id])
		if @post.update(post_params)
			flash[:success] = "投稿を更新しました。"
			redirect_to user_path(current_user)
		else
			render 'edit'
		end		
	end
	
	private
		def post_params
			accessible = [:user_id, :send_user_id, :content, :anonymous, :nickname]
			
			params.require(:post).permit(accessible)
		end
		
		def push_params
			accessible = [:user_id]
			params.require(:push).permit(accessible)
		end
end

app/views/posts/_get_posts.html.erb
<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">

    <%= form_for(@post, html:{class:'form-horizontal'}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :content, placeholder: "Q&A...", class: "form-control", style: "height: 80px;"%>

    <div class="form-group" style="margin-bottom: 0px;">
      <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
      <div class="col col col-md-4 col-sm-4">
        <div class="radio-inline">
          <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
        </div>
        <div class="radio-inline" style="margin-left:0px;">
          <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
        </div>
      </div>
      <%= f.hidden_field :user_id, :value => @this_page_params_user_id %>
      <%= f.hidden_field :send_user_id %>
      <div class="col col col-md-6 col-sm-6">
        <%= f.submit "投稿", class: "btn btn-info", style: "width:100%;margin-top:5px;"%>
      </div>
    </div>
    <div class="form-group" id="nickname-filed" style="display:none;margin-bottom: 0px;">
      <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
      <div class="col col col-md-4 col-sm-4" style="margin-top:5px;">
        <%= f.text_field :nickname, class: "form-control", :placeholder => "匿名" %>
      </div>
    </div>
  </div>
</div>
<% end %>
<%= render 'posts/post' %>

app/views/posts/_post.html.erb
<%= paginate(@posts) %>
<div id="comment">
  <ul class="list-unstyled">
    <% @posts.each do |post| %>
    <li id="">
      <dl id="" style="margin-bottom: 10px;">
        <dd class="date pull-right" style="margin: 5px;">
          <%= post.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </dd>
        <dd>
          <% if @send == 'send' %>
          <a href=<%= "#{user_path(User.find(post.user_id))}"%> style="margin:5px;"><span class="to-name" style="color:#428bca;">to: <%= post.user(post.user_id).family_name + " " + post.user(post.user_id).first_name %></span></a>
          <% end %>
          <div class="userImage">
            <% if(post.anonymous == 0 || post.anonymous.nil?) %>
            <% get_user_main_image(post.user) %><%= @user_pic %>
            <% else %>
            <%= link_to image_tag("default_image.png", :class => 'user-list-image') %>
            <% end %>
          </div>
        </dd>
        <dd class="userName" style="margin-left: 5px;">
          <% if(post.anonymous == 0 || post.anonymous.nil?) %>
          <%= get_user_name_with_link(post.user) %>
          <% else %>
          <%= post.nickname %>
          <% end %>
        </dd>
        <dd class="text" style="margin: 5px;">
          <%= post.content %>
        </dd>
        <% if post.send_user_id == current_user.id %>
        <dd class="text" style="text-align: right;margin: 5px;">
          <%= link_to "編集", edit_post_path(post) %>
        </dd>
        <% end %>
      </dl>
    </li>
    <% end %>
  </ul>
</div>
<%= paginate(@posts) %>

app/views/posts/_post_nav.html.erb
<ul class="nav nav-tabs" style="margin-bottom:20px;">
  <li>
    <% if @is_my_page %>
    <%= link_to "受信したQ&A", user_path(current_user.id) %>
    <% else %>
    <%= link_to "Q&A" %>
    <% end %>
  </li>
  <li>
    <%= link_to "送信したQ&A", posts_send_path if @is_my_page || @send == 'send'%>
  </li>
  <li>
    <a href="#">メッセージ(comming soon)</a>
  </li>
</ul>

app/views/posts/edit.html.erb
<div class="col col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
  <div class="panel panel-default" style="margin-bottom:10px;">
    <div class="panel-heading">

      <%= form_for(@post, html:{class:'form-horizontal'}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_area :content, placeholder: "Q&A...", class: "form-control", style: "height: 80px;"%>

      <div class="form-group" style="margin-bottom: 0px;">
        <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
        <div class="col col col-md-4 col-sm-4">
          <div class="radio-inline">
            <label><%= f.radio_button :anonymous, "0", {:checked => true, :id => "username_button" }%>ユーザー名</label>
          </div>
          <div class="radio-inline" style="margin-left:0px;">
            <label><%= f.radio_button :anonymous, "1", {:id => "anonymous_button"} %>匿名</label>
          </div>
        </div>
        <div class="col col col-md-6 col-sm-6">
          <%= f.submit "更新", class: "btn btn-info", style: "width:100%;margin-top:5px;"%>
        </div>
      </div>
      <% if @post.anonymous == 0 %>
      <div class="form-group" id="nickname-filed" style="display:none;">
        <% else %>
        <div class="form-group" id="nickname-filed">
          <% end %>
          <label for="投稿" class="col col-md-2 col-sm-2 control-label">投稿</label>
          <div class="col col col-md-4 col-sm-4" style="margin-top:5px;">
            <%= f.text_field :nickname, class: "form-control", :placeholder => "匿名" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/posts/posts_send.html.erb
<div class="container">
  <%= notice %>
  <div class="row">
    <div class="col col-md-6 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <ul class="list-unstyled">
            <li class="pull-right">
              <%= button_to "編集", edit_user_path(current_user), {:method => :get, :id => "profile-update", :class => "btn btn-info pull"} %>
            </li>
            <%= render '/users/user_info' %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col col-md-6 col-sm-6">
      <%= render 'post_nav'%>
      <%= render 'post'%>
    </div>
  </div>