config/routes.rb
Rails.application.routes.draw do

  root to: 'users#top'
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/user/:id', to: 'users#show', via: 'get'
  match '/user/:id/edit_detail', to: 'users#edit_detail', via: 'get', :as => :edit_detail
  match '/users/:id/from_twitter', to: 'users#from_twitter', via: 'get', :as => :from_twitter
  match '/users/:id/save_from_twitter', to: 'users#save_from_twitter', via: 'patch', :as => :save_from_save
  
  resources :users do
  	
  end
  
  resources :applicant_records, only: [:create]
  
  resources :advertising, only: [:create, :new, :edit, :update]
  match '/advertising', to: 'advertising#top', via: 'get', :as => :advertising_top
  match '/advertising/search', to: 'advertising#search', via: 'post', :as => :advertising_search
  match '/advertising/search_result/:search', to: 'advertising#search_result', via: 'get', :as => :advertising_search_result
  
  resources :posts, only: [:create, :new, :edit, :update]
  match '/posts/send', to: 'posts#posts_send', via: 'get', :as => :posts_send
  
  namespace "applicants" do
  	
  end
  

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% unless current_user%>
      <a class="navbar-brand" href="/">アルバイトコンシェルジェ</a>
      <% end %>
    </div>

    <% if current_user %>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/"><span class="fa fa-home"></span> home</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% session[:push_count] ||=  current_user.pushes.count %>
          <a href=<%= "#{user_path(current_user)}"%>><span class="fa fa-weixin"></span> メッセージ
          <% if session[:push_count] > 0 %> <span class="badge alert-danger"><%= session[:push_count] %></span> <% end %> </a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdwon-toggle" data-toggle="dropdown"><span class="fa fa-user"></span> <%= current_user.family_name + " "  + current_user.first_name %>さん<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "マイページ", user_path(current_user) %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, :method=> :delete%>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <% else %>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "ログイン", new_user_session_path, {:id => 'login', :class => "headeder-navi"} %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_registration_path, {:id => 'register', :class => 'headder-navi'} %>
        </li>
        <li>
          <%= link_to "お問い合わせ", "mailto:info@arbeit.undo.jp" %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta nanme="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "アルバイトコンシェルジェ"%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :media => "all" %>
    <%= csrf_meta_tags %>

  </head>
  <% unless current_user%>
  <body style="padding-top: 40px;">
  <% else %>
  <body style="padding-top: 60px;">
  <% end %>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<% key %><%= value %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>